# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Debajyoti Mazumder
email: debajyotimaz@gmail.com
logo: /assets/logo_.JPG
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-archives
  - jekyll-diagrams
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-imagemagick
  - jekyll-minifier
  - jekyll-paginate-v2
  - jekyll/scholar
  - jekyll-sitemap
  - jekyll-link-attributes
  - jekyll-twitter-plugin
  - jemoji

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------

scholar_userid: R-b68CEAAAAJ #0htBiCEAAAAJ # your Google Scholar ID

